### ISSUE TITLE
Some of the blog posts have their first letter lost

### ISSUE THREAD

**Issue by ForNeVeR** [AvaloniaUI/avaloniaui.net#157] opened 2020-05-17 14:57 UTC
For example:
- http://avaloniaui.net/docs/quickstart/change-target-framework
  ![image](https://user-images.githubusercontent.com/92793/82152106-5dced900-9889-11ea-9017-c982cbb47b82.png)
- http://avaloniaui.net/docs/quickstart/intro-to-xaml
  ![image](https://user-images.githubusercontent.com/92793/82152110-658e7d80-9889-11ea-9317-9a422a5b9452.png)

**Comment by FoggyFinder** [comment] 2020-05-17 15:37
Duplicate of #153 ?

**Comment by ForNeVeR** [comment] 2020-05-17 15:38
Yeah, thanks!

**Closed** 2020-05-20 09:10 UTC
